"use strict";

module.exports = {
  url: "https://www.if-blog.site",
  title: "アンドロイドは推理小説を書くか?",
  // title: "てすと",
  tagline: "自然言語処理を中心に技術系の記事を書いていきます。最終的には、AIに推理小説を書かせたい。普段はフロント/バックエンド開発。主に使うのは、scala、golang, vue.js, angular、python、keras. コメントはtwitterにお願いします。",
  // tagline: "tag line",
  copyright: "© 2017 if-blog.site, All rights reserved",
  description: "でぃすくりぷしょん",
  author: {
    name: "いふ",
    // name: "author name",
    bio: "bio",
    contacts: {
      linkedin: "",
      github: "https://github.com/if001",
      stackoverflow:"",
      freecodecamp: "",
      twitter: "https://twitter.com/if_004",
    },
  },
  labels: [
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size: 17,
      // color: "deepskyblue",
      color: "royalblue",
    },
    {
      tag: "gatsby",
      tech: "gatsby",
      name: "DiReact",
      size: 17,
      // color: "deepskyblue",
      color: "indigo",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 17,
      color: "green",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGit",
      size: 17,
      // color: "white",
      color: "black",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 17,
      // color: "yellow",
      color: "black"
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 17,
      color: "teal",
    },
    {
      tag: "python",
      tech: "python",
      name: "DiPython",
      size: 17,
      color: "dodgerblue",
    },
    {
      tag: "keras",
      tech: "keras",
      name: "DiPython",
      size: 17,
      color: "red",
    },
    {
      tag: "seq2seq",
      tech: "seq2seq",
      name: "DiPython",
      size: 17,
      color: "dodgerblue",
    },
    {
      tag: "word2vec",
      tech: "word2vec",
      name: "DiPython",
      size: 17,
      color: "dodgerblue",
    },
    {
      tag: "seqgan",
      tech: "seqgan",
      name: "DiPython",
      size: 17,
      color: "dodgerblue",
    },
    {
      tag: "ruby",
      tech: "Ruby",
      name: "DiRuby",
      size: 17,
      color: "crimson",
    },
    {
      tag: "java",
      tech: "Java",
      name: "FaJava",
      size: 17,
      color: "red",
    },
    {
      tag: "angular",
      tech: "Angular",
      name: "DiAngularSimple",
      size: 17,
      color: "red",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 17,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 17,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 17,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 17,
      color: "deepskyblue",
    },
    {
      tag: "go",
      tech: "go",
      name: "DiGo",
      size: 17,
      color: "black",
    },
    {
      tag: "golang",
      tech: "Golang",
      name: "DiGo",
      size: 17,
      color: "black",
    },
    {
      tag: "読書",
      tech: "読書",
      name: "FaBookOpen",
      size: 17,
      color: "blue",
    },
    {
      tag: "読了",
      tech: "読了",
      name: "FaBook",
      size: 17,
      color: "green",
    },
    {
      tag: "hugo",
      tech: "Hugo",
      name: "FaServer",
      size: 17,
      color: "deeppink",
    },
    {
      tag: "falcon",
      tech: "falcon",
      name: "FaServer",
      size: 17,
      color: "dodgerblue",
    },
    {
      tag: "docker",
      tech: "Docker",
      name: "DiDocker",
      size: 17,
      color: "blue",
    },
    {
      tag: "aws",
      tech: "Aws",
      name: "DiAws",
      size: 17,
      color: "orange",
    },
    {
      tag: "nlp",
      tech: "NLP",
      name: "FaLanguage",
      size: 17,
      color: "black",
    },
    {
      tag: "firebase",
      tech: "FireBase",
      name: "DiGoogleCloudPlatform",
      size: 17,
      color: "blue",
    },
    {
      tag: "deeplearning",
      tech: "DeepLearning",
      name: "FaBrain",
      size: 17,
      color: "blue",
    },
    {
      tag: "poem",
      tech: "poem",
      name: "FaPenFancy",
      size: 17,
      color: "sandybrown",
    },
    {
      tag: "rust",
      tech: "rust",
      name: "DiRust",
      size: 17,
      color: "black",
    },
    {
      tag: "tex",
      tech: "tex",
      name: "FaTextHeight",
      size: 17,
      color: "teal",
    },
    {
      tag: "論文",
      tech: "論文",
      name: "FaFileSignature",
      size: 17,
      color: "brown",
    },
    {
      tag: "emacs",
      tech: "emasc",
      name: "FaEdit",
      size: 17,
      color: "purple",
    },
    {
      tag: "google-analytics",
      tech: "google-analytics",
      name: "DiGoogleAnalytics",
      size: 17,
      color: "blue",
    },
    {
      tag: "vue.js",
      tech: "vue.js",
      name: "FaVuejs",
      size: 17,
      color: "green",
    },
    {
      tag: "vuetify",
      tech: "vuetify",
      name: "FaVuejs",
      size: 17,
      color: "blue",
    },
    {
      tag: "android",
      tech: "android",
      name: "FaAndroid",
      size: 17,
      color: "green",
    },
  ],
};
