"use strict";

module.exports = {
  url: "https://developer-diary.netlify.com",
  // title: "アンドロイドは推理小説を書くか?",
  title: "てすと",
  // tagline: "自然言語処理を中心に技術系の記事を書いていきます。最終的には、AIに推理小説を書かせたい。普段はフロント/バックエンド開発。主に使うのは、scala、golang, vue.js, angular、python、keras",
  tagline: "tag line",
  copyright: "© 2019 willjw3, All rights reserved",
  description: "でぃすくりぷしょん",
  author: {
    // name: "いふ",
    name: "author name",
    bio: "bio",
    contacts: {
      linkedin: "",
      github: "https://github.com/if001",
      stackoverflow:"",
      freecodecamp: "",
      twitter: "https://twitter.com/if_004",
    },
  },
  labels: [
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size: 17,
      // color: "deepskyblue",
      color: "black",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 17,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 17,
      // color: "white",
      color: "black",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 17,
      // color: "yellow",
      color: "black"
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 17,
      color: "teal",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 17,
      color: "deepskyblue",
    },
    {
      tag: "ruby",
      tech: "Ruby",
      name: "DiRuby",
      size: 17,
      color: "crimson",
    },
    {
      tag: "java",
      tech: "Java",
      name: "FaJava",
      size: 17,
      color: "wheat",
    },
    {
      tag: "angular",
      tech: "Angular",
      name: "DiAngularSimple",
      size: 17,
      color: "red",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 17,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 17,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 17,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 17,
      color: "deepskyblue",
    },
  ],
};
